### PR TITLE
Upgrade stable xcsoar to 7.2

### LINKED ISSUE #39: scale font size for InfoBoxes
The font in the InfoBoxes, particularly the label and the comment are awfully small.
I've been looking around in the source but can't find anything.
The font scaling on the map window works as expected.
Does anybody have an idea??
p4

BTW: a screenshot function would be so nice. ;-)

### LINKED ISSUE #120: Voltage indicator
Hello,
the battery voltage indicator is not working in "stable" image version. But it does work fine in the testing one.
The voltage_config parameter was set the same in sensord.conf file. Tried on recent images 21038 (both compiled on 06.02.2021).

### PR DESCRIPTION
**Pull request by kedder**
XCSoar 7.0 was just released. Upgrade stable image to 7.0.

Fixes #39 
Fixes #120

### CODE REVIEW

**Comment by kedder** [comment]
Meanwhile, xcsoar-7.1 was released. @linuxianer99 does this look good to you?

**Comment by DanD222** [comment]
@kedder What do you think about including this as a patch before 7.2 gets released? https://github.com/XCSoar/XCSoar/commit/4faceeb5d0c6aa58b12e3e0e58e955842000155f
(original issue: https://github.com/XCSoar/XCSoar/issues/557)

It should have a pretty big impact on OpenVario, i.e. make navigation to Alternates usable with the remote stick.

**Comment by kedder** [comment]
@DanD222, this is in XCSoar master, as I understand, so it will end up in testing version anyways.

**Comment by DanD222** [comment]
Ah, nice.. 7.2 is actually out now, so it might be worth another bump? Perhaps also cutting a new image afterwards?

**Comment by kedder** [comment]
Alright, upgraded straight to 7.2

**Review by linuxianer99 — APPROVED** [review]

**Pull request merged**
