### PR TITLE
Fixrotation

### PR DESCRIPTION
**Pull request by lordfolken**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
The second commit will break existing configurations

**Comment by linuxianer99** [comment]
ok, we wait with mergeing until #256 is fixed ?

**Comment by MaxKellermann** [comment]
This is supposed to be the fix for #256, but it solves it in a way that breaks compatibility with existing configurations.
You could "don't care", then everybody "just" has to reconfigure the rotation, and we'd get rid of some cruft complexity, that's good. Both is ok for me. It just needs to be an explicit decision, and not some "oops we broke it".

**Comment by linuxianer99** [comment]
ok... i see ..
I will merge, as we have a lot of huge changes at the moment ... so this will be no problem :-)

**Pull request merged**
