### PR TITLE
improve backup and restore procedure

### PR DESCRIPTION
**Pull request by Blaubart**
This backup script stores all XCSoar settings and relevant OpenVario settings like:

- brightness of the display
- rotation
- touch screen calibration
- language settings
- dropbear settings
- SSH, variod and sensord status

backups are stored at USB stick at:
- openvario/backup/"MAC address of eth0"/

So you can store more than one backup on the same stick!

We add system info script, too

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This is now a different kind of horrible mess.

**Comment by Blaubart** [comment]
Why??

**Comment by MaxKellermann** [comment]
The diff is also very confusing. The commit does many different and independent things, but one commit should only do one thing.

**Comment by MaxKellermann** [comment]
What this PR seems to be doing:
- add stuff to .gitignore
- add some system-info feature
- new script transfer-xcsoar
- removing several old scripts
- lots of whitespace changes in ovmenu-ng.sh
- moving code around
- at the same time, modify the code that was moved around
- and maybe more, I can't see, I'm so confused

All of this is very confusing, and code review is nearly impossible.

**Comment by 7lima** [comment]
So we have 2 elements here, the backup/restore and the system info which have both been completely reworked. Furthermore the file and function names have been renamed. I understand that it's a lot to swallow as a single chunk. Would you prefer if we divided the PR into 2 or 3 parts?

**Comment by MaxKellermann** [comment]
Note that I don't manage this project, I just state my opinion here (without being asked to).
On my projects, I expect contributors to write PRs where each commit is self-contained and documented, each commit is known-good (no known defects, and no fixup commits in the same PR), and each commit contains only one change (which may be spread across multiple files, so all code modifications belonging to that change are in the one commit, but not more than one unrelated change in one commit).

If you were about to improve the backup procedure, that should be one commit, but that commit should not rename scripts, because that would obfuscate the changes and would make reviewers unable to see what you were trying to improve.
If you were about to add a system info feature, that doesn't belong in a commit that also improves backup/restore.
You could suggest adding patterns to .gitignore, but that should be a separate commit, and the commit message should explain why this pattern is needed. (If this pattern is specific to your own workflow, it should be in your own private .gitignore file and not merged in this public repository.)

Many different changes can be put in one PR, but as separate commits.

**Comment by Blaubart** [comment]
Hi Max,

thanks for your explanations!! We are working on taking this into account in the future and making it better.

**Comment by 7lima** [comment]
I'll separate the different functional items into coherent commits building upon each other. Then you may have a look again.

**Comment by linuxianer99** [comment]
Hi All,
i share the opinion of @MaxKellermann . 
So have a different features in different commits also makes a potential bug fixing a lot easier, if this comes necessary ...

Having multiple commits in on PR is fine ...

You can also have a look here:
https://github.com/Openvario/meta-openvario/wiki/Code-Contribution-Rules

**Pull request closed without merging**
