### PR TITLE
correct path of usb stick mountpoint to /usb/usbstick

### PR DESCRIPTION
**Pull request by lordfolken**
implements #226

### CODE REVIEW

**Comment by linuxianer99** [comment]
I think we have to check all download scripts of the ovmenu tools ...
The path for usb stick mount is hardcoded there ...
@lordfolken have you keep this in mind ?

**Comment by lordfolken** [comment]
This PR is because the scripts presently expect the stick to be on /usb/usbstick. 
Currently the usbstick gets an addtional directory usbstick/openvario instead of just openvario.

I'm also revamping the scripts, as there are a lot of pitfalls that are currently not handled. (special chars, spaces, subdirectories..)

**Comment by lordfolken** [comment]
Could we merge this?

**Review by kedder — APPROVED** [review]
LGTM

**Comment by kedder** [comment]
There are conflicts though, can't merge

**Comment by linuxianer99** [comment]
@kedder : i am not at home at the moment ..  there is a merge conflict, so it is difficult to merge for me on the mobile ;-) Can you do the merge please ?

**Comment by kedder** [comment]
Hm, I'm not sure what is the right resolution here. @lordfolken, can you take a look at the git config?

**Pull request merged**
