### PR TITLE
Update XCSoar, kernel, Yocto

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by mihu-ov** [comment]
Just a general question: should we use the latest stable linux kernel, or the latest longterm supported kernel for best stability?

**Review by linuxianer99 — APPROVED** [review]
LGTM

**Comment by MaxKellermann** [comment]
> Just a general question: should we use the latest stable linux kernel, or the latest longterm supported kernel for best stability?

That's a question of taste.
If you only use longterm kernels, you have bigger steps between the versions, which makes upgrades much more complicated, and you keep postponing the updates because they are so complicated.
Using latest stable means smaller steps, but more often. That quickly becomes an easy routine. I prefer that.

**Comment by mihu-ov** [comment]
Thank you for the explanation!

**Comment by August2111** [comment]
From my point of view it should be merged asap... (XCSoar 7.24!)

**Pull request merged**
