### PR TITLE
Improve XCSoar recipe in regard to lua

### PR DESCRIPTION
**Pull request by linuxianer99**
- install lua as lua5.4.pc
- Enable lua detection of XCSoar build system
- Restructure XCSoar build recipe in regard to SRC_URI

### CODE REVIEW

**Comment by linuxianer99** [comment]
@August2111 : Please review !!

**Review by August2111 — COMMENTED** [review]
Merging the 2 changes of xcsoar-*.bb  together with remove of unused patch is ok

**Review by August2111 — COMMENTED** [review]
Ok

**Comment by August2111** [comment]
...fine :)

**Pull request merged**
