### PR TITLE
Reducing the image size

### PR DESCRIPTION
**Pull request by August2111**
Reduce the image size to 1GB for the possible usage of 1GB sd card!

- Maybe this should be aligned later to a common sd card size

### CODE REVIEW

**Comment by kedder** [comment]
I would not do this, because when OV goes out-of-space, XCSoar crashes. And I had such an event midflight during WGC2021 :) Takes an extraordinary amount of hacking skills to diagnose the situation and work around it using only the arrow buttons on the stick :)

Out-of-space can happen pretty easily if you have NMEA logging on.

**Comment by August2111** [comment]
> Out-of-space can happen pretty easily if you have NMEA logging on.
Of course there is a good point - I know! But for this reason I want to discuss about the location, access rights, size and so on at issue #156. With big maps - without cleanup between you can also running in this out of space very fast!
At least a warning should be happens, if the memory has only a free space of some megabytes...
So I will postbone this PR after this discussion!

**Comment by MaxKellermann** [comment]
This change is bad; instead of hard-coding an image size, the filesystem should be expanded to the full size of the SD card on first boot. This can be done easily with [systemd-repart](https://www.freedesktop.org/software/systemd/man/systemd-repart.html).
Also, there should be separate partitions for the operating system and data, to allow updating the firmware without erasing all data.

**Comment by DanD222** [comment]
Pardon me for being obtuse, but what is the benefit of reducing the image size to fit on a 1GB SD card in an age when high capacity SD cards are cheap and plentiful?

**Comment by kedder** [comment]
@DanD222 as I understand the main benefit is quicker turn-around when a developer tries a new build. Flashing 1GB is 4 times faster than flashing 4GB and you have to do it a lot of times when debugging the image. Our current set up limits the available free space to 1GB though, so it is not great. @MaxKellermann basically suggests the same thing we have agreed on in #156, which is a win-win - making image small and quick to flash, and also using all available flash space.

**Comment by DanD222** [comment]
@kedder OK, that sounds good, thanks for the explanation!

**Comment by MaxKellermann** [comment]
The image could be just 50 MB (with a compressed read-only system partition). The data partition spanning the rest of the SD card would then be initialized on the first boot. You can flash an OpenVario within a couple of seconds that way...

**Comment by August2111** [comment]
Ok, all this stuff was the main idea behind this commit/pr: reducing the os partition and create a big data partition, so we discussed in #156 this idea - and at the end we will bring this ideas together in a new PR - so I will close this one to make the way free for the next steps...

**Pull request closed without merging**
