### PR TITLE
Enable lima driver and switch to DRM/KMS drivers for graphics 

### PR DESCRIPTION
**Pull request by kedder**
This (eventually) will allow using all opengl infrastructure and use of lima drivers for openvario.

In particular:

* Update kernel config parameters to compile sunxi drm modules and lima drivers. The diff for `defaultconfig` is so big because I upgraded the config to what `make menuconfig` generates, to track canges more easily.
* Upgrade mesa to fresh 19.3.3 version to have latest opengl support for lima driver
* Backport the LVDS support for A20, provide device tree for kernel to enable

### CODE REVIEW

**Comment by kedder** [comment]
_This is not yet ready to merge_. ATM `openvario.dts` hardcodes 5.7" display parameters. They need to be split into separate devicetrees for each of the display variations.

**Comment by kedder** [comment]
> Do you copy them from Yocto or openembedded project? There are so many files which make reviewer difficult.

Yes, I did copy and bump the version.  I think it would be better to split this into several MRs, but I'm postponing this after I get my patch into the kernel - it gets a bunch of corrections after reviews.

**Comment by kedder** [comment]
> Is this used? Without this file, kernel is compiled.

Um, I think github lost the context if this message. What file was it?

**Comment by CazYokoyama** [comment]
> > Is this used? Without this file, kernel is compiled.
> 
> Um, I think github lost the context if this message. What file was it?

I mean arm/defconfig. Do are overwrite meta-sunxi/recipes-kernel/linux/linux-mainline/arm/defconfig? meta-openvario makes meta-sunxi/recipes-kernel/linux/linux-mainline/arm/defconfig as a base and modify by kernel_conf_variable() in linux.inc, correct?

**Comment by kedder** [comment]
@CazYokoyama yes, `arm/defconfig` is the main configuration file for the kernel. I did notice the kernel doesn't compile in this MR and it probably has something to do with the config, but hadn't had a chance to figure it out yet.

**Comment by kedder** [comment]
I can try to fix it tomorrow, if you want to play with this. Let me know.

**Comment by kedder** [comment]
Ok, I cleaned up the patch and removed mesa from it. It enables DRM/KMS on kernel and configures the screen (still 5.7" only). XCSoar runs, but on emulated simple framebuffer only (i.e. no rotation).

**Comment by linuxianer99** [comment]
@kedder : Shoud i merge this PR now ?

**Comment by kedder** [comment]
@linuxianer99 wait a bit, I'm making flavor-specific device tree files, should be done soon

**Comment by kedder** [comment]
@linuxianer99 I adapted DT settings for other supported panels, except 43-rgb variant. That doesn't look like LVDS panel, and I don't want to guess device tree bindings for it - I can't test it. For other panels I adapted settings from the u-boot configs, should be good.

I think this MR is ready to merge now.

**Comment by CazYokoyama** [comment]
Does it work? XCSoar does not accept mouse input.

**Comment by kedder** [comment]
@CazYokoyama hm, works for me - both (wireless) usb mouse and keyboard  works in xcsoar.

**Comment by CazYokoyama** [comment]
Are you using warrior branch on poky, meta-openembedded, meta-sunxi and meta-openvario? Are you able to show me your build commands? Are you able to send me img.gz?

**Comment by kedder** [comment]
Yes, these are my layers: 

```
BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  ${TOPDIR}/../sources/poky/meta \
  ${TOPDIR}/../sources/poky/meta-poky \
  ${TOPDIR}/../sources/poky/meta-yocto-bsp \
  ${TOPDIR}/../sources/meta-sunxi \
  ${TOPDIR}/../sources/meta-openvario \
  ${TOPDIR}/../sources/meta-openembedded/meta-oe \
  ${TOPDIR}/../sources/meta-openembedded/meta-python \
  ${TOPDIR}/../sources/meta-openembedded/meta-networking \
  "
```

Here's the link to my latest build: https://www.dropbox.com/s/9p38hcjtdynuij3/OpenVario-linux-openvario-image-testing-glibc-ipk-current-openvario-57-lvds.rootfs.img.gz?dl=0

**Comment by CazYokoyama** [comment]
Disregard my problem regarding mouse input. I connected the mouse to another system.

**Comment by kedder** [comment]
Good to hear!

**Pull request merged**
