### PR TITLE
Hardknott update for Openvario

### PR DESCRIPTION
**Pull request by August2111**
This is a full running Hardknott update for layer meta-openvario.

Of course this is a 1st trial - don't hesitate to check all features :)

### CODE REVIEW

**Review by linuxianer99 — APPROVED** [review]
Locks good ...

**Review by linuxianer99 — APPROVED** [review]

**Review by linuxianer99 — APPROVED** [review]

**Review by linuxianer99 — APPROVED** [review]

**Review by linuxianer99 — APPROVED** [review]

**Review by linuxianer99 — APPROVED** [review]

**Review by kedder — APPROVED** [review]
I remember I had to also upgrade the docker build container to the latest Ubuntu LTS. Is this image buildable on the old container?

**Comment by linuxianer99** [comment]
@kedder : Yes, the container has to be updated as well. This is already done see openvario/ovbuild-container :-)

**Comment by kedder** [comment]
Great job @August2111, thanks for the effort!

**Comment by August2111** [comment]
> Great job @August2111, thanks for the effort!

Thank you very much - and behind this changes aI learned a lot about layers, recipes and all this staff. Hopefully the next switch to a newer Yocto system will be much easier - at least for me :)

**Comment by linuxianer99** [comment]
@August2111 : I also started a build for testing :-) Great work !!

**Pull request merged**
